### ISSUE TITLE
mas/yr to km/s converter in bovy_coords or units

### ISSUE THREAD

**Issue by pkaf** [jobovy/galpy#267]
add mas/yr to km/s converter in bovy_coords or units

**Comment by jobovy** [comment]
Could you elaborate on this please? mas/yr cannot be converted into km/s, you need the distance for that. Do you mean a function that takes a proper motion and turns it into a linear velocity?

**Comment by pkaf** [comment]
Yes, I mean a function that would take distance/parallax. It is a trivial calculation but still due to 4.7 factor and the units involved makes it a useful function to have.

**Comment by jobovy** [comment]
I agree that it would be useful, but I think this is more something for [astropy](http://github.com/astropy/astropy)'s units package, where you should be able to do
```
from astropy import units
print (2.*units.mas/units.yr*3.*units.kpc).to(units.km/units.s)
```

This doesn't currently work, because astropy cannot convert these units properly, but I would encourage you to raise this as an issue at the astropy repository (when you do this you can reference this issue as jobovy/galpy#267). I'm adding functionality to use astropy's units throughout galpy (and move away from supporting unit conversions within galpy itself) and so it would be better to fix this closer to the source.

**Comment by pkaf** [comment]
In the case that you are moving away from supporting unit conversion I think it makes sense to use  astropy unit package then. I will try to raise the issue there.

**Comment by jobovy** [comment]
By the way, I recently realized that what you want is possible in a somewhat roundabout way as follows. You can initialize an orbit as [RA,Dec,distance,pmRA,pmDEC,vlos] and then ask for vra, which will give you the proper motion converted to a linear velocity
```
from galpy.orbit import Orbit
pmra, pmdec, distance= 2., 4., 3. #mas/yr, mas/yr, kpc
o= Orbit([10.,10.,distance,pmra,pmdec,0.],radec=True)
o.vra(), o.vdec() # km/s
array([ 28.44282]), array([ 56.88564])
```
