### ISSUE TITLE
zmin or ev value calculate

### ISSUE THREAD

**Issue by oguzhanatas** [jobovy/galpy#276]
Hi,
I am working on orbital parameters of some stars via this package,It includes "zmax" and "ep" and I need to "zmin" or "ev" value but I didn't. If you know how I find it or calculate, can you say it?

**Comment by jobovy** [comment]
For all of the potentials, z=0 is a symmetry plane and every orbit passes through it. So zmin is always zero. Maybe I'm misunderstanding what you want? I also don't know what you mean by "ep" and "ev", please clarify.

**Comment by oguzhanatas** [comment]
so why zmin cannot be negative since orbits pass trough below the galactic plane? and ep and ev are meaning eccentricity but "ev" is veritical eccentricity so that ev=(zmax-zmin)/(zmax+zmin)

**Comment by jobovy** [comment]
I see what you mean. Because ``z=0`` is a symmetry plane, ``zmin = - zmax``. That is, stars go as far below the ``z=0`` plane as they go above it, because of the symmetry of the gravitational potential.

If you have a potential that you are using that breaks the symmetry, you can always get zmin as np.amin(o.zs(times)) for an orbit o and integration times ``times``.

**Comment by oguzhanatas** [comment]
i got it.
thank you for your support.
