### ISSUE TITLE
meanjz() error

### ISSUE THREAD

**Issue by RuthAngus** [jobovy/galpy#300]
Hi Jo, 

I ran your example, http://galpy.readthedocs.io/en/latest/diskdf.html and tested the estimate_hr() and meanvz() functions which seem to work fine. But when I try >>> qdf.meanjz(1., .125)
I get the error:  TypeError: quad() got multiple values for argument 'func'

Do you know what's going on?

**Comment by jobovy** [comment]
I don't get this error, can you post the exact code and the full error output? Please use [pastebin](http://pastebin.com/) if the error message is too large. What version of scipy are you using?

**Comment by RuthAngus** [comment]
I'm using version 0.18.1. The full error message is here: http://pastebin.com/1uCPz9WT

```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from galpy.potential import MWPotential2014
from galpy.actionAngle import actionAngleStaeckel, actionAngleAdiabatic
from galpy.df import quasiisothermaldf

# Bovy example
aA = actionAngleAdiabatic(pot=MWPotential2014, c=True)
hr = 1/3.  # radial scale length
sr = .2  # radial velocity dispersion at the solar radius (time dependent)
sz = .1  # vertical velocity dispersion at the solar radius (time dependent)
hsr = 1.  # radial-velocity-dispersion scale length
hsz = 1.  # vertial-velocity-dispersion scale length

qdf = quasiisothermaldf(hr, sr, sz, hsr, hsz, pot=MWPotential2014, aA=aA,
                        cutcounter=True)
print(qdf.estimate_hr(1.))
print(qdf.meanvz(1., 0.))
print(qdf.meanjz(1., .125))
```

**Comment by jobovy** [comment]
Thanks! This seems to be a bug that I'll have to fix (I know what the problem is). However, for your purposes you probably want to make sure that the C extensions are installed (in which case this code does work), because that will be orders of magnitude faster. Let me know if you have any problem with installing the C extensions (there's quite a bit in the [installation guide](http://galpy.readthedocs.io/en/latest/installation.html) about this).

**Comment by RuthAngus** [comment]
Ok, I will! Thanks so much!

**Comment by jobovy** [comment]
This should be fixed now in ``master``.
