### ISSUE TITLE
Astropy Affiliated Package Review

### ISSUE THREAD

**Issue by astrofrog** [jobovy/galpy#316]
This package has been re-reviewed by the Astropy coordination committee in relation to the Astropy affiliated package ecosystem.

We have adopted a review process for affiliated package that includes assigning quantitative ‘scores’ (red/orange/green) for different categories of review. You can read up more about this process [here](https://docs.google.com/document/d/15PJf2PROXMa7xwTDvWnjXB_9KNuO2Ia4_kkxJ7MPazE/edit). (This document, currently in Google Docs, will be moved to the documentation in the near future.) For each of the categories below we have listed the score and have included some comments when the score is not green.

<table>
<tr><td><b>Functionality/Scope</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.pch9wiwetm2l"><img src="https://img.shields.io/badge/Functionality-Specialized%20package-brightgreen.svg" alt="Specialized%20package"></a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Integration with Astropy ecosystem</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.lizp0k629jgg"><img src="https://img.shields.io/badge/Astropy%20integration-Partial-orange.svg" alt="Partial"></a></td></tr>

<tr><td colspan=2><i>There are still some areas, in particular coordinates, where there could be closer integration with the astropy.coordinates package (but in other places integration with astropy is good)</i></td></tr>

<tr><td><b>Documentation</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.prawoqxdnwj5"><img src="https://img.shields.io/badge/Docs-Good-brightgreen.svg" alt="Good"></a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Testing</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.8dots8fmtpvp"><img src="https://img.shields.io/badge/Tests-Good-brightgreen.svg" alt="Good"></a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Development status</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.zh2jxv4intgn"><img src="https://img.shields.io/badge/Development-Good-brightgreen.svg" alt="Good"></a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Python 3 compatibility</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.9tur152fuipe"><img src="https://img.shields.io/badge/Python%203-Good-brightgreen.svg" alt="Good"></a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

</table>

**Summary/Decision**: Things are looking good! There are some areas where things could be improved as described above. However, these aren't critical and this package still meets the criteria to be an affiliated package. Keep up the good work!

If you agree with the above review, please feel free to close this issue. If you have any follow-up questions or disagree with any of the comments above, leave a comment and we can discuss it here. At any point in future you can request a re-review of the package if you believe any of the scores should be updated - contact the coordination committee, and we’ll do a new review. Note that we are in the process of redesigning the http://affiliated.astropy.org page to show these scores (but not the comments). Finally, please keep the title of this issue as-is (“Astropy Affiliated Package Review”) to make it easy to search for affiliated package reviews in future.

**Comment by jobovy** [comment]
I'm glad to hear the galpy has passed muster (again) as an affiliated package, but I do think that posting this here is an inappropriate use of the Issues feature in GitHub. An astropy review is not an ''issue'' in any way for the code and posting it as such disrespects the work of the galpy developers. I also take offense at the official tone taken in this posting, as if astropy's review is some sort of official review of galpy and as if astropy is supervising galpy's development. So I must ask you to not post these types of review in the future and simply contact the code maintainer by email about this.

About the coordinate transformation ''partial integration'', I find this continuous harping on about my not fully using astropy's coordinate package unproductive. I made significant efforts to use astropy's coordinate framework and indeed it [is the default option now in galpy](https://github.com/jobovy/galpy/blob/master/galpy/util/config.py#L15) for users who have astropy installed. However, in tests I have found astropy's unit conversions to be significantly slower than my own implementations because of the large overhead coming from the (overall very useful of course) coordinate framework. In addition, my code implements velocity transformations which until a few months ago were not in astropy yet, are still in a somewhat experimental state, and which do not fully cover my code's need (and they are also likely slower than my own implementations). So I prefer to keep my own versions for now, rather than waste my own time and computational time in using astropy's routines. For me, this is another symptom of the wider problem with astropy not fostering diversity in approaches in the astronomical software community: these are simply internal routines in my code that I am in no way advertising as an alternative to astropy's coordinate routines, but somehow astropy just cannot take the fact that these exist.
