### ISSUE TITLE
interpotential/angleadiabatic warning

### ISSUE THREAD

**Issue by nbanik** [jobovy/galpy#317]
Hi, 

  I am trying to install galpy as --user on my university cluster and I am getting the following warnings. 

galpyWarning: interppotential_c extension module not loaded, because of error '/home/nilanjan1/.local/lib/python2.7/site-packages/galpy-1.2-py2.7-linux-x86_64.egg/galpy_interppotential_c.so: undefined symbol: __kmpc_end_serialized_parallel' 
galpyWarning: actionAngleAdiabatic_c extension module not loaded, because of error '/home/nilanjan1/.local/lib/python2.7/site-packages/galpy-1.2-py2.7-linux-x86_64.egg/galpy_actionAngle_c.so: undefined symbol: __kmpc_end_serialized_parallel' 
galpyWarning: actionAngleStaeckel_c extension module not loaded, because of error '/home/nilanjan1/.local/lib/python2.7/site-packages/galpy-1.2-py2.7-linux-x86_64.egg/galpy_actionAngle_c.so: undefined symbol: __kmpc_end_serialized_parallel' 

I was careful to specify the gsl paths as shown under FAQs in the installation page. My aim is to use galpy for running your streamgap-pepper codes with openMP so that I can parallelize computation of streams with multiple impacts. Will these warnings have any consequences towards this?

Thanks,
Nil

**Comment by jobovy** [comment]
Hi Nil,

I think you must be compiling galpy with the intel compiler ``icc`` rather than with ``gcc``? I never use ``icc``, but it seems like the problem might be that the OpenMP compile flag is ``-openmp`` rather than ``-fopenmp`` in ``gcc``. So you could try changing [this line](https://github.com/jobovy/galpy/blob/master/setup.py#L34) to have ``-openmp``.

Even if this doesn't work, unless you are using an`` interpRZPotential`` this does not affect the stream-pepper code, which doesn't use the C modules that aren't working (are you sure you can integrate orbits in C? ``from galpy.orbit import Orbit`` does not give a warning?). So it shouldn't matter too much for what you want to do, but please let me know whether the above fix works, because then I could edit the setup file to take into account ``icc``.

The streamgap-pepper code is not parallelized with OpenMP.

**Comment by nbanik** [comment]
Thanks, that's exactly what the problem was.
