### ISSUE TITLE
Orbital parameters differ depending on galpy version?

### ISSUE THREAD

**Issue by astrodietz** [jobovy/galpy#332]
I noticed that using MWPotential2014 with galpy 1.1 gives one set of results (ecc, Z_max, etc.) while using it with galpy 1.2 or 1.3 gives another. Has the form of this potential significantly changed since 1.1?

(I can provide the code used & the input/output if needed.)

**Comment by jobovy** [comment]
``MWPotential2014`` hasn't changed, but depending on how you are computing the orbital parameters the method for computing these may have changed. Code with input and output to illustrate this would be appreciated!

**Comment by astrodietz** [comment]
Thanks for your response, here's some code and output files to show what I mean.

import numpy as np
from astropy import units
from galpy.orbit import Orbit
from galpy.potential import MWPotential2014 as mw

ro, vo = 8., 220.0

ra = 227.805163529 # [deg]
dec = -21.500936162 # [deg]
distance = 7.1
pm_ra = -4.1 # [mas/yr]
pm_dec = -21.0 # [mas/yr]
v_hel = 14.4 # [km /s]

ts = np.linspace(0, 10, 10000) * units.Gyr
o1 = Orbit(vxvv=[ra, dec, distance, pm_ra, pm_dec, v_hel],radec=True, ro=ro, vo=vo)
o1.integrate(ts, mw)
    
print "\norbital parameters:\n"
print "rap = {}".format(o1.rap())
print "rperi = {}".format(o1.rperi())
print "ecc = {}".format(o1.e())
print "zmax = {}".format(o1.zmax())

[MW14_galpy1pt1.txt](https://github.com/jobovy/galpy/files/1733981/MW14_galpy1pt1.txt)
[MW14_galpy1pt2.txt](https://github.com/jobovy/galpy/files/1733982/MW14_galpy1pt2.txt)
[MW14_galpy1pt3.txt](https://github.com/jobovy/galpy/files/1733983/MW14_galpy1pt3.txt)

**Comment by jobovy** [comment]
Thanks for digging into this. It is difficult to be sure of what is going on here. The orbit you are trying to integrate is clearly highly eccentric, so the slightest change to the ``galpy`` algorithms can give a very different result. ``MWPotential2014`` is only constrained by data out to ~50 kpc, so the potential outside of that is very uncertain and this orbit goes beyond that.

One thing that changed between 1.1 and 1.2 is that I fixed the conversion from (l,b,d,...) to Galactocentric coordinates (previously the code didn't take into account that the Galactic plane is tilted wrt the b=0 plane; this makes a very small difference for most objects). Because you are initializing the orbit with ra,dec,... that could have changed the orbit in Galactocentric coordinates by a small amount, enough to for this orbit make a big difference in its apocenter.

You could check this by seeing what the ``[R,vR,vT,z,vz,phi]`` coordinates of this orbit are in the different galpy versions. Do
```
RvR= [o1.R(),o1.vR(),o1.vT(),o1.z(),o1.vz(),o1.phi()]
```
and check how different these are. You can then try to take the ``RvR`` from galpy v1.1 and integrate it with v1.2 or v1.3 and see whether you then get the same result as you now get in v1.1 (or vice versa):
```
o1= Orbit(vxvv=RvR,ro=ro,vo=vo)
```
with the appropriate ``RvR`` should do this.

If this is the difference, then the newer versions are more accurate (but again, if ``rap`` >> 50 kpc, then you should take ``rap`` with a grain of salt anyway because of the uncertainty in the potential and ``MWPotential2014`` is but one choice for the potential).

**Comment by astrodietz** [comment]
Just an update, I followed your suggestion (using the RvR obtained from the 1.1 orbit and using it to integrate the 1.3 orbit), and the results don't seem to change much. The RvR used is listed below, output attached.

RvR = [2.9629043556117791, 173.96946550868606, -329.66977621820945, 3.6575554912202723, -404.43403082359771, -0.72243411955474435]

I tested what the initial vx, vy, and vz values were for each version, since those values would be affected by a coordinate conversion difference between versions 1.1 and 1.2/1.3, but the difference is small.

1.1:
vx=77.3702144214
vy=-586.34858613
vz=-411.134030824

1.2:
vx=77.3693640751
vy=-586.348697502
vz=-411.134032012

[MW14_galpy1pt3_v2.txt](https://github.com/jobovy/galpy/files/1742043/MW14_galpy1pt3_v2.txt)

**Comment by jobovy** [comment]
Thanks for checking this. I used ``git bisect`` to figure out which commit made the difference and in hindsight the answer is rather obvious: in v1.1 you were not allowed to specify the time of the integration as a Quantity and the time was *always* interpreted as being in internal units (and apparently the 'Gyr' was silently dropped, so there was no error; v1.1 was before astropy unit support). So you were effectively integrating for a very different length of time in v1.1 (10 in internal units is only a few 100 Myr in physical units). The code is correct in v1.2/v1.3.

If you do the conversion instead directly using
```
from galpy.util import bovy_conversion
ts = np.linspace(0, 10, 10000)/bovy_conversion.time_in_Gyr(vo,ro)
```
then you get the same answer in all versions (except for the small difference due to the difference in the coordinate transformation from above).

**Comment by astrodietz** [comment]
I tested my code with the conversion provided and the results match much better now. Thanks for all your help!

[MW14_galpy1pt1_newts.txt](https://github.com/jobovy/galpy/files/1744927/MW14_galpy1pt1_newts.txt)
[MW14_galpy1pt3_newts.txt](https://github.com/jobovy/galpy/files/1744928/MW14_galpy1pt3_newts.txt)
