### ISSUE TITLE
scipy logsumexp now located in scipy.special

### ISSUE THREAD

**Issue by henrysky** [jobovy/galpy#364]
`galpy` should use the new logsumexp import for scipy>=1.0.0 (`scipy.special.logsumexp`)

official msg:
`logsumexp is deprecated! Importing logsumexp from scipy.misc is deprecated in scipy 1.0.0. Use scipy.special.logsumexp instead.`

**Comment by jobovy** [comment]
Change seems to have happened in scipy v0.19; now fixed in ``galpy``.

**Comment by ahriley** [comment]
Are there plans to fix this (or at least flag it in the docs) for the stable `v1.4` (and maybe even earlier)? 

For instance, running
```
conda create -n test galpy
conda activate test
python
```
and then
```
from galpy.orbit import Orbit
```
gives an `ImportError: cannot import name 'logsumexp' from 'scipy.misc'`, which doesn't really agree with the Installation instructions saying that conda is the easiest way to install.

**Comment by jobovy** [comment]
The hope is to release a new version of galpy soon that will contain the fix, but that is probably a few months away. You're right that I should probably backport that fix since without it the entire conda build is broken (and I do have a maintenance/1.4.x branch for exactly this purpose). I might have some time next week to fix this. Do you happen to know whether there are any other similar v1.4 bugs that should be backported? I'll re-open the issue for now...

**Comment by ahriley** [comment]
After fixing the imports in `streamdf.py`, `FullOrbit.py`, and `DiskSCFPotential.py`, everything seems to be fine.

There is an `AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed` when importing `Orbit`.

**Comment by jobovy** [comment]
Thanks! Not sure where that astropy warning is coming from, I don't think we use that library explicitly.

**Comment by jobovy** [comment]
A version ``1.4.1`` with a fix for this issue is now on conda, so the conda installation should work again. Please test! Thanks.

**Comment by ahriley** [comment]
everything working fine on my end!

**Comment by jobovy** [comment]
Great, thanks for checking!
