### ISSUE TITLE
Improve the Python leapfrog integrator

### ISSUE THREAD

**Issue by jobovy** [jobovy/galpy#365]
The python implementation of leapfrog does not make use of the fact that drifts can be combined when not storing output, causing it to be slower than necessary. Comparing to the C implementation, it also appears to not be as precise.

**Comment by jamesgrimmett** [comment]
Hi @jobovy,

I was recently looking at the Python leapfrog integrator, due to a missing a C implementation for a Potential that I was looking to use (`PowerTriaxialPotential`). I ended up finding `TriaxialNFWPotential` which fits my use case and has a C implementation. Anyway, I figured that I would post my leapfrog findings here.

Is something like this what you had in mind for combining the drifts?

```
    for ii in range(1, len(t)):
        # drift
        q12 = leapfrog_leapq(qo, po, dt / 2.0)
        for jj in range(ndt):  # loop over number of sub-intervals
            # kick                                                                                                     force = func(q12, *args, t=to + dt / 2.0)
            po = leapfrog_leapp(po, dt, force)
            # drift
            q12 = leapfrog_leapq(q12, po, dt)
            # Get ready for next
            to += dt
        # Half step back for final output
        qo = leapfrog_leapq(q12, po, -dt / 2.0)
        out[ii, 0 : len(yo) // 2] = qo
        out[ii, len(yo) // 2 : len(yo)] = po
```

I tried this and unfortunately/surprisingly it seems to make only a minor improvement in running time (smaller than the variation in running time between consecutive runs). I tested the change with a profiling script (https://gist.github.com/jamesgrimmett/0efa7638a13ffcfbc9dea424c5220e75), and it looks like the time spent in the leapfrog_leap functions is negligible compared to the force calculation, hence the small impact on execution time. I've pasted the output from the profiling script below.

```
$ python profile_script.py
         55463016 function calls (49702710 primitive calls) in 19.911 seconds

   Ordered by: cumulative time
   List reduced from 99 to 50 due to restriction <50>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   19.911   19.911 Orbits.py:1338(integrate)
        1    0.000    0.000   19.911   19.911 integrateFullOrbit.py:714(integrateFullOrbit)
        1    0.001    0.001   19.911   19.911 integrateFullOrbit.py:766(integrate_for_map)
        1    0.235    0.235   19.911   19.911 symplecticode.py:38(leapfrog)
   320015    0.717    0.000   19.146    0.000 integrateFullOrbit.py:1236(_rectForce)
   320015    0.351    0.000    7.394    0.000 Potential.py:2310(_evaluatezforces)
   320015    0.346    0.000    7.302    0.000 Potential.py:2176(_evaluateRforces)
   960046    1.472    0.000    5.771    0.000 DissipativeForce.py:173(_isDissipative)
   640030    4.932    0.000    5.618    0.000 PowerSphericalPotentialwCutoff.py:205(_mass)
   960045    0.208    0.000    4.111    0.000 Potential.py:239(_zforce_nodecorator)
   960045    0.215    0.000    3.912    0.000 Potential.py:201(_Rforce_nodecorator)
   320015    0.321    0.000    3.652    0.000 Potential.py:2243(_evaluatephitorques)
   320015    0.322    0.000    3.134    0.000 PowerSphericalPotentialwCutoff.py:103(_zforce)
   320015    0.321    0.000    3.127    0.000 PowerSphericalPotentialwCutoff.py:99(_Rforce)
3840180/960045    1.106    0.000    3.036    0.000 Potential.py:3911(_isNonAxi)
  1920091    0.513    0.000    2.844    0.000 fromnumeric.py:2979(prod)
  1920096    0.824    0.000    2.331    0.000 fromnumeric.py:71(_wrapreduction)
   960051    0.464    0.000    1.868    0.000 Potential.py:3807(flatten)
  1920101    1.390    0.000    1.390    0.000 {method 'reduce' of 'numpy.ufunc' objects}
6720358/3840200    1.321    0.000    1.321    0.000 Potential.py:3799(_flatten_list)
 16640860    0.769    0.000    0.769    0.000 {built-in method builtins.isinstance}
  2880147    0.662    0.000    0.662    0.000 {built-in method numpy.array}
   640030    0.493    0.000    0.566    0.000 numeric.py:203(ones_like)
  1920105    0.265    0.000    0.437    0.000 <frozen importlib._bootstrap>:645(parent)
   320015    0.411    0.000    0.425    0.000 MiyamotoNagaiPotential.py:77(_zforce)
   320015    0.349    0.000    0.349    0.000 TwoPowerSphericalPotential.py:887(_Rforce)
   320015    0.344    0.000    0.344    0.000 TwoPowerSphericalPotential.py:895(_zforce)
   960045    0.304    0.000    0.304    0.000 Potential.py:749(_phitorque_nodecorator)
   360025    0.266    0.000    0.266    0.000 symplecticode.py:95(leapfrog_leapq)
   320015    0.259    0.000    0.259    0.000 symplecticode.py:99(leapfrog_leapp)
```

Interestingly though, I notice that there is a fairly significant amount of time being spent in `_isDissipative` (and similarly, to a lesser degree in `_isNonAxi`). They're each being called three times for every iteration of the inner leapfrog loop, via `_rectForce` -> [`_evaluateRforces`, `evaluatephitorques`, `evaluatezforces`]. I ran a simple test by setting by hand each instance of `nonAxi = False #_isNonAxi(Pot)` and `dissipative = False #_isDissipative(Pot)` and see close to a 50% reduction in running time. I am only assuming that there isn't any case where these checks would need to be done more than once for any integration.

I'm not sure whether there is a simple change to remove these calls from the loop, but I'd be happy to have a go at making some improvements if you're keen and able to provide some guidance.

Some initial thoughts on a few different options for avoiding the need for these calls;
-  Add an initial check (prior to the integration) of the potentials/arguments to ensure necessary information has been passed for non-axisymmetric/dissipative potentials. It looks like something like this has been done for the C implementation. Perhaps the check function could then be called from `Potential.evaluateRforces`, `Potential.evaluatephitorque`, and `Potential.evaluatezforces`, and removed from the corresponding underscored functions?
- Add a `@cache` decorator (from `functools`) to the `_isDissipative` and `_isNonAxi` functions to cache the result between calls. This seems to work just as well as my initial test of manually bypassing the calls (i.e., setting to False by hand) with a 50% reduction in runtime. The downside is that this requires some other code changes, as Pot needs to be converted to a tuple (if it is a list) before being passed to the functions for compatibility with `functools.cache`.
 - Create a very simple `PotentialList` class for storing lists of Potentials, with `nonAxi` and `isDissipative` attributes. Then, the checks could be done easily for either case (singular or PotentialList) with `Pot.nonAxi` and `Pot.isDissipative`.

Keen to hear what you think, and whether you'd be happy for me to go ahead and make a start on a fork+PR for these improvements.

**Comment by jamesgrimmett** [comment]
Thanks for the feedback @jobovy, moving those checks to the underscored functions sounds like the most sensible approach. I'll try it out and see whether is causes issues for any of the tests. 

I will also play around with also adding some kind of `_isDissipative` attribute to avoid the need to re-check for each Potential/Force, and maybe some other small changes to align the Python implementation a bit more with the C code. I suppose performance of the Python integrators is not a high priority for the project, but I've resolved to contributing more to open source projects so this seems like a good place to start!

I can understand the reluctance to add a `CompositePotential` class, and I'm not even sure whether the benefits would outweigh the change. Using a list is nice and simple, and avoids unneeded complexity for the user. On the other hand I can imagine that a `CompositePotential` class might allow the removal of a lot of the internal checks/conditionals for treating singular vs. multiple Potentials appropriately. Automatic internal conversion of lists to a `CompositePotential` sounds like an ideal solution to me, if it does turn out to simplify the internal logic by a significant amount. I'm not sure where this would fall on your priority list for the project, but it might be something that I could look at, even if only as a way to gain better understanding of the source code.

**Comment by jobovy** [comment]
> Thanks for the feedback @jobovy, moving those checks to the underscored functions sounds like the most sensible approach. I'll try it out and see whether is causes issues for any of the tests.

Thanks, that would be great and very helpful!
 
> I will also play around with also adding some kind of `_isDissipative` attribute to avoid the need to re-check for each Potential/Force, and maybe some other small changes to align the Python implementation a bit more with the C code. I suppose performance of the Python integrators is not a high priority for the project, but I've resolved to contributing more to open source projects so this seems like a good place to start!

Yes, in general I haven't worried too much about the performance of the Python integrators (or action-angle coordinate transforms), because users who need speed can just use the C version of the code (which these days installs pretty reliably, although still not 100% and issues keep coming up...). But it would definitely be nice if the Python integrators could be more efficient, e.g., when implementing a new potential to see how it works before doing the hard work of implementing it in C or when users define their own potential (which is currently impossible to easily get to work in C).

> 
> I can understand the reluctance to add a `CompositePotential` class, and I'm not even sure whether the benefits would outweigh the change. Using a list is nice and simple, and avoids unneeded complexity for the user. On the other hand I can imagine that a `CompositePotential` class might allow the removal of a lot of the internal checks/conditionals for treating singular vs. multiple Potentials appropriately. Automatic internal conversion of lists to a `CompositePotential` sounds like an ideal solution to me, if it does turn out to simplify the internal logic by a significant amount. I'm not sure where this would fall on your priority list for the project, but it might be something that I could look at, even if only as a way to gain better understanding of the source code.

Yes, one of the main reasons to introduce `CompositePotential` would be to remove the specialized code for dealing with single vs. lists of potentials. For example, it would allow the eventual removal of the `evaluatePotentials` etc. functions, because composite potentials could then also just be evaluated (or use `.Rforce` rather than `evaluateRforces`). Although for backwards compatibility, we'd have to keep the old functions for a while.... Internally, the code wouldn't immediately get much simpler, because the logic for dealing with singular vs. multiple Potentials appropriately would just move into `CompositePotential`, but having everything in a single class might make it easier to figure out simpliciations/speed-ups (like the `_isDissipative` keyword, or upon initialization of a `CompositePotential`, one could split the potential into dissipative and non-dissipative contributions and then avoid checks, e.g., in the `Rforce` calculation, because that could just become `Rforce = Rforce_nondiss(pot_nodiss) + Rforce_diss(pot_diss)`, where the latter returns zero if there are no dissipative components; this could then even be used to speed up the C code in a similar way perhaps).
