### ISSUE TITLE
Inconsistent behaviour of dop853 when integrating from a nonzero initial time step

### ISSUE THREAD

**Issue by mwbub** [jobovy/galpy#390]
The behaviour of the dop853 and dop853_c integrator changes when the initial time step of the integration is nonzero. In particular, the integrator seems to behave as if the initial conditions of an Orbit always occur at t=0. An example is as follows:

```python
import numpy as np
import matplotlib.pyplot as plt
from galpy.orbit import Orbit
from galpy.potential import MWPotential2014

method = 'dop853_c'

t1 = np.linspace(0, 5, 100)
o1 = Orbit()
o1.integrate(t1, MWPotential2014, method=method)

t2 = np.linspace(5, 10, 100)
o2 = Orbit()
o2.integrate(t2, MWPotential2014, method=method)

o1.plot(d1='x', d2='y')
o2.plot(d1='x', d2='y')
plt.show()
```

This results in these plots:
![image](https://user-images.githubusercontent.com/28573452/60841473-eb3c9980-a19f-11e9-8864-4e7306faf3c1.png)
![image](https://user-images.githubusercontent.com/28573452/60841510-fb547900-a19f-11e9-9557-ac34aac28284.png)
which show that when integrating from a nonzero initial time step, the integrator immediately jumps to the final time step of the first plot, and continues from there. 

When replacing `method = 'dop853_c'` with `method = 'symplec4_c'`, the plots are consistent with one another. Also, this issue occurs for both the C and Python implementations of the dop853 integrator.

**Comment by henrysky** [comment]
I will take a look and fix `dop853` for the case of nonzero initial time that the zeroth element still returning the value at `t=0`, the zeroth element should be the value at the zeroth element in the time array instead of `t=0`.

I am not so sure about the point of `inconsistent behavior` on nonzero initial time is a bug? I personally think the initial time should be `t=0` and so I have coded `dop853` in that way. In the second case the initial time is still `t=0` and it just happens you want `t=5` to `t=10`, otherwise why one will specify 5 to 10 instead of 0 to 5 (just my personal opinion)?

And internally, `dop853` will do adaptive time steps it determined to be the best considering a specific error tolerance and your current location in the potential, and extrapolate to those times you want in the time array you provided (so your time array can even be unevenly spaced). So one has motivation to do `t=5` to `t=10` in the performance standpoint instead of `t=0` to `t=10` and then get `t=5` to `t=10`, that it integrating from `t=0` to `t=5` using the largest possible steps and start extrapolating from `t=5` to `t=10`

To illustrate  this is what I thought the 2 should look like, but still will wait Jo to take a look on this
![image](https://user-images.githubusercontent.com/28623434/60847329-4f675980-a1b0-11e9-9bcd-1be20b43132a.png)

**Comment by mwbub** [comment]
I understand the motivation behind coding it in this way, but in my view it is problematic for a number of reasons:

Firstly, it is inconsistent with the behaviour of the other galpy integrators (for instance, replace `dop853_c` with `symplec4_c` in my example above). Thus, if you wanted the code to behave this way, you would essentially have to change every other integrator as well to avoid confusion.

Secondly, it becomes difficult to precisely control one's initial conditions in many cases, for instance when working with time-dependent potentials. In these cases, it is not always true that you would want to start an integration at t=0.

As you said, Jo has the final word on this, but I believe the behaviour of the other galpy integrators is more natural.

**Comment by henrysky** [comment]
You are right this is indeed an issue. I have never thought of the consistency issue probably because I have never tried to integrate orbit with non-zero initial time with other integrator, I see your point now.

**Comment by henrysky** [comment]
@mwbub I think the commit fixed the issue

also one can skip the in between value if just want `t=5` to t=`10` by inserting an extra t=0 to the front of time array to represent the initial condition is indeed at `t=0`. Does this behavior look natural to you??

```
import numpy as np
import matplotlib.pyplot as plt
from galpy.orbit import Orbit
from galpy.potential import MWPotential2014

method = 'dop853_c'

# integrate all the way from 0 to 10
t1 = np.linspace(0, 10, 201)
o1 = Orbit()
o1.integrate(t1, MWPotential2014, method=method)

# only get dense output for t=5 to t=10
t2 = np.linspace(5, 10, 101)
t2 = np.insert(t2, 0, 0.)  # use t=0 as initial
o2 = Orbit()
o2.integrate(t2, MWPotential2014, method=method)

# assert the two methods return the same result to 12 decimals
np.testing.assert_array_almost_equal(o1.x(t1[100:]), o2.x(t2[1:]), decimal=12)
```

**Comment by mwbub** [comment]
I would think this adresses the issue; thanks for getting on top of this so quickly.

For reference, I came across this issue when trying to write a checkpointing system for another piece of code that uses galpy (so I wanted to break up an integration into several pieces, and start each piece using the final time step of the previous piece as the new initial condition). This should solve that for me when it is merged, so thanks again.

**Comment by jobovy** [comment]
I agree with @mwbub that the expected behavior should be that if you ask to integrate from 5 to 10, then the first returned value should be at 5 and not zero. As Mathew says, for a time-dependent potential the actual time does indeed matter, so you can't just shift (5 to 10) to (0 to 5). And I think Mathew's use case of integrating for a while and then starting from the previous last value is pretty common, so good to support.

@henrysky: so the fix does what I suggest above? It will correctly integrate (5 to 10) without putting in the t=0 value? Interesting point that `dop853` is the only integrator for which the times can be evenly spaced (although I think `odeint` can also do this).

**Comment by henrysky** [comment]
@jobovy Yes, the fix produces the same plot as other integrator for original Mathew's code.

**Comment by jobovy** [comment]
Great, I'll merge the PR then once the tests pass.
