### ISSUE TITLE
Orbit SkyCoord initialization fails quietly when radec=True is set

### ISSUE THREAD

**Issue by jjensen4571** [jobovy/galpy#402]
Hi all,

I recently made the unfortunate mistake of updating my OS to Catalina. Before this update, galpy was functioning fine. I needed to reinstall all anaconda and all python packages and I have found that my code no longer calculates the orbits correctly. I am not sure exactly the differences between Catalina & Mojave other than the update removed all python packages and put them in "Relocated Items" (hence why I reinstalled everything). I have attached some plots to show the issue.

Mainly I think what I noticed is the integration does not start at my object ngc5466, but instead starts at the position of the sun. Thanks in advance for looking into this.

Cheers,
Jaclyn
![orbittest](https://user-images.githubusercontent.com/44014199/67178327-28135180-f387-11e9-84c7-f85c0bb4ef53.png)

**Comment by jjensen4571** [comment]
Here is the code used to create the first orbit plot
`rv_ngc5466 = 106.93
rv_error_ngc5466 = 0.18
pmra_ngc5466 = -5.41
pmra_error_ngc5466 = 0.01
pmdec_ngc5466 = -0.79
pmdec_error_ngc5466 = 0.01 
ra_ngc5466 = 211.363708
dec_ngc5466 = 28.534445
rhel_ngc5466 = 16.0
rhel_error_ngc5466 = 0.4


mean_ngc5466 = SkyCoord( ra = ra_ngc5466 * u.deg, dec = dec_ngc5466 * u.deg, distance = rhel_ngc5466 * u.kpc, pm_ra_cosdec = pmra_ngc5466 * u.mas / u.yr, pm_dec = pmdec_ngc5466 * u.mas / u.yr, radial_velocity = rv_ngc5466 * u.km / u.s )

n_steps = 100
times = np.linspace( 0, 0.1, n_steps ) * u.Gyr

#leading
o = Orbit( mean_ngc5466, radec = True, ro = 8.1, vo = 229.0, solarmotion = "schoenrich" )
o.integrate( times, MWPotential2014, method = 'symplec4_c' )

x_f = o.x( times )
y_f = o.y( times )
z_f = o.z( times )
ra_f = o.ra( times )
dec_f = o.dec( times )

#trailing
o.flip( inplace = True )
o.integrate( times, MWPotential2014 )

x_b = o.x( times )
y_b = o.y( times )
z_b = o.z( times )
ra_b = o.ra( times )
dec_b = o.dec( times )

plt.plot( ra_f, dec_f, label = 'Leading' )
plt.plot( ra_b, dec_b, label = 'Trailing' )
plt.plot( ra_6, dec_6, 'k.', label = 'Cluster Points' ) #from cluster data of NGC 5466
plt.xlabel( 'RA' )
plt.ylabel( 'Dec' )
plt.plot( ra_ngc5466, dec_ngc5466, 'rx', markersize = 15, label = 'NGC 5466 Start' )
plt.legend( loc = 'best' )`

**Comment by jobovy** [comment]
I don't think this is an issue with the "MacOS Catalina Update/Anaconda 2019.10", since I get the same results on my older Mac version. I think the issue is that when you give the initial condition of an orbit as a ``SkyCoord``, you cannot set ``radec=True``, because things seem to go wrong then. 

I consider this to be a bug, so I will rename the issue and leave it open until it's fixed, but for now you can just remove ``radec=True`` from the orbit initialization and I think it will work fine then.

**Comment by jjensen4571** [comment]
Thanks; this did fix the issue for me as well. Also, if the parameters are input to orbit as variables and not SkyCoord objects, then it also works. What I had noticed that also might suggest it is an issue with astropy.coordinates is that the option to use Orbit.from_name did not seem to reproduce the graphic seen in the Documentation. The orbit is produced below.
![Screen Shot 2019-10-25 at 12 00 32](https://user-images.githubusercontent.com/44014199/67597994-4a0f2a00-f721-11e9-8a81-36d40204fac6.png)

**Comment by jobovy** [comment]
I think that the Omega Cen issue is because the documentation was produced a while ago, when Omega Cen's phase-space coordinates were obtained using SIMBAD, but in the latest version of galpy, Omega Cen's phase-space coordinates are hard-coded to be those obtained from Gaia DR2 (this is the case for almost all globular clusters now).

You can force the SIMBAD look up by using a form that galpy can't parse into the hard-coded name, like 
```
o= Orbit.from_name('Omega Centauri')
```
although that also seems to give a different orbit than in the documentation, probably because the SIMBAD coordinates have been updated as well. Because ``from_name`` gets the latest SIMBAD parameters for an object, these are not stable, so if you're using ``from_name`` for research, you should probably save the coordinates it returns so that you always use the same ones.
