### ISSUE TITLE
a small problem with the intel compiler option

### ISSUE THREAD

**Issue by r-xue** [jobovy/galpy#416]
It looks like I have to set `--no-openmp` when using `--inplace --compiler=intelem`. Otherwise, the flag `-lgomp` will still be handed over to `icc` and mine is not happy about that. 

Maybe automatically have `--no-openmp` on when the `icc` is called, or mention this in the documentation. `-qopenmp` is in the default `icc` configuration already.

though, I am not sure if this is a local issue as I am using the newest `icc`:
```
hyperion:galpy Rui$ icc --version
icc (ICC) 19.1.0.166 20191121
```

thanks for your hard work!

**Comment by jobovy** [comment]
@henrysky, you've looked at using the Intel compiler before, could you take a look? I don't have an Intel compiler installed.

**Comment by henrysky** [comment]
@r-xue can you specify what kind of error are you getting? I can compile galpy with icc 19.1 without any issue with the command line mentioned in the document

**Comment by r-xue** [comment]
@henrysky The log is attached. Thanks for looking into this.
[icc_galpy.log](https://github.com/jobovy/galpy/files/4270466/icc_galpy.log)

**Comment by henrysky** [comment]
@r-xue I believe this is a MacOS specific issue (the error is documented here too: https://galpy.readthedocs.io/en/latest/installation.html#i-m-having-issues-with-openmp). I think you need to do something like `brew install clang-omp` to install the openmp support for your compiler since `clang` has no OpenMP support according to the docs (I do not have MacOS so I cannot say for sure, @jobovy will probably know what is the status of OpenMP with `clang` on MacOS).

**Comment by jobovy** [comment]
Okay, so it seems like the issue is that ``icc`` comes with ``OpenMP`` included (see [here](https://stackoverflow.com/questions/6482845/icc-on-linux-link-to-openmp), so there is no need to link to the ``libomp`` library. I agree that it is confusing to have to specify ``--no-openmp`` to get OpenMP to work with the intel compiler.

Seems like an easy fix would be to move the part of the ``setup.py`` file where the intel compiler is supported (currently [here](https://github.com/jobovy/galpy/blob/master/setup.py#L98)) to above the part where the ``--no-openmp`` flag is processed and then use ``use_intel_compiler `` the part of ``setup.py`` that parses the ``--no-openmp`` flag to remove the OpenMP stuff. I don't know whether the Intel compiler would ever be the default (i.e., not set by ``--compiler=intelem``), because then this wouldn't work.

I'll leave this open and label it as ``good first issue`` and see whether anybody wants to fix this. If not, I'll fix it before releasing the next version.
