### ISSUE TITLE
Orbit plot doesn't work

### ISSUE THREAD

**Issue by oguzhanatas** [jobovy/galpy#431]
Hi Professor,

I have a problem.
when I try to draw plot, there are nothing. The code ran and done. Plot command ( '**op.plot()**' second to last line in the gedit ) seems like doesn't work... 
I shared the screenshot (code and terminal screen).
![bovy_galpy_v3](https://user-images.githubusercontent.com/19612227/92308540-feffad80-efa6-11ea-87cc-018f835995ff.png)

Best regards,

**Comment by jobovy** [comment]
Hi! 

Getting the plot the show up depends on your ``matplotlib`` setup. The documentation assumes you're using something like a jupyter notebook with ``%pylab inline`` at the top, or are using iPython started with ``ipython --pylab``. Then plots just display without requiring any further action Otherwise, you might have to run [``matplotlib.pyplot.show()``](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.show.html) or save the figure with [``matplotlib.pyplot.savefig()``](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.savefig.html). Hope that helps!

**Comment by oguzhanatas** [comment]
> Hi!
> 
> Getting the plot to show up depends on your `matplotlib` setup. The documentation assumes you're using something like a jupyter notebook with `%pylab inline` at the top, or are using iPython started with `ipython --pylab`. Then plots just display without requiring any further action. Otherwise, you might have to run [`matplotlib.pyplot.show()`](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.show.html) or save the figure with [`matplotlib.pyplot.savefig()`](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.savefig.html). Hope that helps!

Thank you very much for prompt reply to my message!
i forgot to add the command (**plt.show()**).

Best regards,
