### ISSUE TITLE
Question about the coordinate transformation

### ISSUE THREAD

**Issue by lwang-astro** [jobovy/galpy#442]
I tried to use astropy.SkyCoord (frame= 'galactocentric' ) as an input for Orbit. 
But I found that after read the data and integrate the orbit using the following sample script, the plot from Galpy has a different sign of x and vx compared to the originial input SkyCoord. I feel it is confusing. What should be done correctly here to get a consistent coordinate between Galpy and astropy.SkyCoord? 

By the way, I use the galpy 1.6 installed from Python3 pip3 

```
import numpy as np
import astropy 
from astropy.coordinates import SkyCoord  
import astropy.units as u
import galpy
from galpy.orbit import Orbit

cord = SkyCoord(x=1*u.kpc,y=1*u.kpc,z=1*u.kpc,v_x=100*u.km/u.s,v_y=100*u.km/u.s,v_z=-100*u.km/u.s,
                frame='galactocentric',representation_type='cartesian')
gal_int=Orbit(cord)
gal_int.integrate(np.linspace(0,10,10)*u.Myr,galpy.potential.MWPotential2014)
gal_int.plot(d1='x',d2='y')
gal_int.plot('.k',d1='vx',d2='vy')
```

**Comment by jobovy** [comment]
Yes, `galpy` uses a left-handed coordinate frame, whereas `astropy` uses a right-handed one (as well documented in the documentation). There is currently no way to say that you want `galpy` to work in a right-handed coordinate frame and there likely will not be one any time soon, because it seems like it would complicate many parts of the code without much pay-off. However, if you want the output from an orbit integration in a right-handed coordinate frame, you could ask for the output as a `SkyCoord` (`Orbit.SkyCoord`) and then get the output in any way you want using `SkyCoord`'s capabilities.

**Comment by lwang-astro** [comment]
Thank you for the quick response! 
I try to use `gal_int.SkyCoord` (in the above sample script). It only print the initial condition. 
How to print the full integration data to SkyCoord?

**Comment by jobovy** [comment]
You should give it the time(s) at which you want the output, so
```
gal_int.SkyCoord(np.linspace(0,10,10)*u.Myr)
```
to get a `SkyCoord` array at the output times.

**Comment by lwang-astro** [comment]
Thank you! Sorry I have missed the description of SkyCoord in the documentation. Now I found it by using the searching function in the documentational website.
