### ISSUE TITLE
Incorrect enclosed mass calculation for the SCFPotential class 

### ISSUE THREAD

**Issue by MariusCautun** [jobovy/galpy#448]
The enclosed mass for the SCFPotential gives incorrect results. This can be seen, for example, by calculating the gravitational constant as the ratio "G = -radialForce * r**2 / enclosed_mass". For example, calculating G using the SCFPotential and the NFW_Potential using:

from galpy.potential.McMillan17 import McMillan_bulge as SCF_example
from galpy.potential.McMillan17 import McMillan_halo as NFW_example

print( np.array([SCF_example.rforce(r,0.)*-r**2/SCF_example.mass(r) for r in np.logspace(-1.,1,11)]) )
print( np.array([NFW_example.rforce(r,0.)*-r**2/NFW_example.mass(r) for r in np.logspace(-1.,1,11)]) )

gives:

[4.15961053e-11 4.07422059e-11 3.93095052e-11 3.69516234e-11
 3.45853909e-11 3.35434633e-11 3.31871985e-11 3.30513410e-11
 3.30003584e-11 3.29798669e-11 3.29712882e-11]

[6.52571641e-11 6.52571641e-11 6.52571641e-11 6.52571641e-11
 6.52571641e-11 6.52571641e-11 6.52571641e-11 6.52571641e-11
 6.52571641e-11 6.52571641e-11 6.52571641e-11]

The first result is clearly not correct since the result depends on radius.  I checked that the mass values obtained using .mass(r) return values ~2 too large. The circular velocity estimate is correct, so I suspect that the error is in the enclosed mass calculation.

A similar error is seen for the enclosed mass calculation for DiskSCFPotential, although there is a warning not to trust the enclosed mass calculation.

A simple way to estimate the spherically average enclosed mass is from Gauss' theorem: the surface integral of rforce is proportional to the enclosed mass.

**Comment by jobovy** [comment]
Hi Marius,

Thanks for the issue. Some questions/comments:

* Is this with the latest version of the `master` branch? I just updated the calculation of the enclosed mass and in particular for `SCFPotential`. I think you may be using the older version where just specifying `r` in `.mass(r)` assumed the potential is spherical (the McMillan17 bulge is not).
* I think your results are for `print( np.array([SCF_example.rforce(r,0.)/(-SCF_example.mass(r)/r**2) for r in np.logspace(-1.,1,11)]) )`? That is, the ratio rather than the difference.
* The bulge in McMillan17 is not spherical, so Fr = -GM(<r)/r^2 does not hold. So you don't expect the ratio to be constant for the bulge. Of course at r >> rbulge, you should get the same ratio as for the spherical NFW, but at least in my version of `master` that's the case.

Good point about Gauss' theorem! I should probably use that to simplify the calculation of the enclosed mass.

**Comment by MariusCautun** [comment]
Hi Jo,

I am using the latest master version on MacOS. When I do galpy.__version__ I get "1.7.0.dev0". But I do use the C-binaries from the latest release (I think it is 1.6) since was easier than compiling the master version ones. Could the error be because the calculation takes place in the C-files? I checked and I get the same results in galpy 1.6 and 1.5.

There was a mistake in my previous post due to markdown formating rules, the code I run was indeed the ratio:
```python
from galpy.potential.McMillan17 import McMillan_bulge as SCF_example
from galpy.potential.McMillan17 import McMillan_halo as NFW_example

print( np.array([SCF_example.rforce(r,0.)*-r**2/SCF_example.mass(r) for r in np.logspace(-1.,1,11)]) )
print( np.array([NFW_example.rforce(r,0.)*-r**2/NFW_example.mass(r) for r in np.logspace(-1.,1,11)]) )
```
with the  output
```python
[4.15961053e-11 4.07422059e-11 3.93095052e-11 3.69516234e-11
 3.45853909e-11 3.35434633e-11 3.31871985e-11 3.30513410e-11
 3.30003584e-11 3.29798669e-11 3.29712882e-11]
[6.52571641e-11 6.52571641e-11 6.52571641e-11 6.52571641e-11
 6.52571641e-11 6.52571641e-11 6.52571641e-11 6.52571641e-11
 6.52571641e-11 6.52571641e-11 6.52571641e-11]
```

**Comment by jobovy** [comment]
Hi Marius,

Okay, yes, this has been fixed less than 2 weeks ago! (and I even switched to using Gauss' theorem yesterday, but that doesn't change the result) You might want to update your branch using
```
git pull https://github.com/jobovy/galpy.git master
```
I think that should work... If you want to be on the safe side you could do something like
```
git checkout -b upstream-master
git pull https://github.com/jobovy/galpy.git master
```
and if all goes well do
```
git checkout master
git merge upstream-master
```

Note that generally it is recommended to not make changes to the `master` branch of your fork, but rather make a branch for each PR, so like `git checkout -b cautun20` for creating a branch to add your potential. Unfortunately, you can't change the source branch of a PR, so it's best to leave it as your `master` now, otherwise you'd have to close the PR and open a new one...

Just to close the loop on the issue: the issue is that until the recent changes, calling `mass` with a single coordinate calculated the mass assuming spherical symmetry using the density along `z=0`. Because the bulge is flattened by a factor of 0.5, this led to the factor of two discrepancy in your result. In the current version, calling `mass` with a single coordinate does the proper integral over the spherical region.
