### ISSUE TITLE
Problem with number of spirals generated by SpiralArmsPotential()

### ISSUE THREAD

**Issue by Lekshmi288** [jobovy/galpy#449]
According to the documentation N=2 gives two spirals. But, in the density plot of this potential, it has 4 spirals. 
![sparm](https://user-images.githubusercontent.com/35341935/112654427-61be7680-8e1d-11eb-8941-5aebcf8084b3.png)

Here is the code I used:
`pot=SpiralArmsPotential(ro=1,N=2,amp_units='density',amp=1.3)
plotDensities(pot,t=0, rmin=-1,rmax=1, nrs=100, zmin=-1, zmax=1, nzs=100,
                phi=0, xy=True, ncontours=10, savefilename=None, aspect=None, log=False, justcontours=True)`

Whereas when using MWPotential2014+SpiralArmsPotential(ro=1,N=2,amp_units='density',amp=1.3), it returns a perturbed potential with 2 spirals as expected:
![image](https://user-images.githubusercontent.com/35341935/112653815-cb8a5080-8e1c-11eb-8fdf-f88909f7caf7.png)

After wrapping the SpiralArmsPotential:
`csp=GaussianAmplitudeWrapperPotential(pot=CorotatingRotationWrapperPotential(pot=SpiralArmsPotential(ro=1,N=2,am     p_units='density'), vpo=1.,to=to,ro=1),ro=1,to=to,amp=100,sigma=1.)`

`pot=MWPotential2014+csp
plotDensities(pot,t=0, rmin=-1,rmax=1, nrs=100, zmin=-1, zmax=1, nzs=100,
                phi=0, xy=True, ncontours=20, savefilename=None, aspect=None, log=False, justcontours=True)`

This gives again 4 spirals with N=2. 
![image](https://user-images.githubusercontent.com/35341935/112654261-350a5f00-8e1d-11eb-94a9-b53e42e92667.png)

Couldn't find anything like this explained in the documentation. Any help would be much appreciated!

**Comment by jobovy** [comment]
Yes, this is confusing and had me stumped for a little bit! But what's going on is that the `SpiralArmsPotential` is a modulation around zero density and when you do a contour plot, the underdense regions look like arms as well. That is, half of the arms that you see are the under-dense counterpart of the over-dense spirals. If you do `justcontours=False` you'll see that the density is different in half of the arms, which is because it's negative there.

I added a note to the `SpiralArmsPotential` docs to point out this confusing situation.
