### ISSUE TITLE
King Density Profile Returning NaN on Fitting Attempts

### ISSUE THREAD

**Issue by jeramkaram** [jobovy/galpy#455]
Hi there,
I have recently been trying to put together fits of a density profile to a King profile using the galpy.df.kingdf routine. However, there are certain values of r_t and W0 that, when passed into the King routine, return NaN at large radii. I understand that the King model does not extend to infinity like, say a Plummer model, but my question is:
Are these NaNs intentional? Are they there just to imply that the density profiled no longer exists at these radii? If so, are there any recommendations for fitting methods that can get around this problem? Thank you for the help.
Jeremy

**Comment by jobovy** [comment]
Hi @jeramkaram, without an actual example, it's hard to know what's happening here, but generally the density returned will be NaN if r > rt. For some extreme values of W0, the calculation also breaks down, so you'll probably want to constrain the range of W0 to a reasonable range in the fit (W0=1 or 2 to a few tens to a hundred I think work fine, W0 much larger becomes essentially a singular-isothermal-sphere rho ~ 1/r^2). If the issue is that you have stars with r > rt that you are trying to fit, then you need some background model added to the fit, because they can't be part of the cluster in such a model; you could for example just add a constant density, so the density is rho_king(r) + small constant density.

Happy to look at this in more detail if you send an example of what goes wrong.

**Comment by jeramkaram** [comment]
Thanks for the fast response. I think your latter comment is helpful. A more detailed version of the problem is:
I have a star cluster with a number of star and gas particles and I can find a density profile of stellar component of the cluster. I'm then trying to fit a King model to that profile. An example of where this seems to go wrong is when my King model has best fit parameters W0 = 10.9104 and rt = 3.559. This is outputting 0s at the very end of my density profile. A quick post-dinner analysis has just shown that this best fit value of rt corresponds exactly with my outermost bin which would line up with what you were saying where density values beyond or at rt are expected to get to 0. It seems like something is wrong with the fitting method for these specific clusters. The image of the fit looks something like this.
![denss341](https://user-images.githubusercontent.com/28263115/122140959-5f672980-ce1a-11eb-834d-eeeca8b4f0dc.png)

**Comment by jobovy** [comment]
I think this may be because of a numerical instability in the unit handling, because for the default conversion to internal units, 3.5 pc gets converted to `rt=0.0004375` in internal units and that seems to lead to numerical issues because it's so small. However, you can easily change the conversion to internal units, for example, the following works for me
```
from galpy.df import kingdf
from astropy import units as u
%pylab inline
dfk= kingdf(W0=10.9104,M=2.3,rt=3.559*u.pc,ro=10*u.pc)
rs= numpy.geomspace(0.01,3.55,101)*u.pc
loglog(rs,[dfk.dens(r) for r in rs])
xlabel(r'$r$')
ylabel(r'$\rho(r)$');
```
(note that I just used an arbitrary mass here)

To make sure that you are using consistent physical <--> internal unit conversions, you can change `ro` in the [configuration file](https://docs.galpy.org/en/latest/installation.html#configuration-file); `ro` there is in kpc, so for 10 pc you'd have to set `ro= 0.00125` there. You might also want to adjust `vo` to a GC-like value (like the typical velocity in a cluster); `vo` is in km/s.

**Comment by jeramkaram** [comment]
I think I see, but just so I'm sure I understand:
The parameter rt I pass into `kingdf` is expected to be in pc and the conversion `kingdf` is doing into internal `galpy` units is resulting in an rt that is too small. Therefore, when I change the unit conversion parameter `ro` this will prevent `rt` from getting too small. Furthermore, the functions `parse_length` and `parse_mass` help identify the units, but by default, `parse_length` returns a kpc unit hence the need for a change in ro and the lack of a unit definition such as `u.solMass` for the `M` parameter.
Am I sort of getting it?

**Comment by jobovy** [comment]
Yes, this is mostly how it goes, but just to be explicit:
* If you specify rt as 10*u.pc `parse_length` converts it to `rt/ro` internally, where ro=8 kpc by default. But you can change ro either globally through the configuration file or locally when initializing the class. 
* If you don't add astropy units, the code assumes that the parameter is in internal units. So M=2.3 is mass in internal units. I just used M=2.3 because I didn't care about the mass, but it's easiest to set it like `M=10000*u.Msun` with units as well.
* `parse_length` and other `parse_` functions convert to internal units
* The conversion to and from internal units is fully specified by `ro` and `vo`, all other conversions are just functions of those two basic parameters.

**Comment by jeramkaram** [comment]
Understood. Thanks very much for taking the time to walk through this with me. I think this will help my fits.
