### ISSUE TITLE
Should you always specify ro and vo for the orbit integration?

### ISSUE THREAD

**Issue by kassidy-kollmann** [jobovy/galpy#465]
Hi, I'm currently using galpy to model a dwarf satellite galaxy orbiting a larger MW-sized galaxy. I prefer to work in physical units, so I am currently initializing the orbit with all initial positions and velocities specified with astropy units. I'm currently not setting ro or vo because I read in the documentation that it is not necessary to specify these when the initial conditions are set with physical units, and also when you do input and output in physical units (both of which I am doing). But out of curiosity I ran a simple test run of the orbit integration with and without specifying ro and vo, and I see that the two orbits are quite different. Can you please help me understand why this is the case? Should I always be specifying ro and vo, even if giving the initial conditions in physical units and receiving the output in physical units?

Thank you!

**Comment by jobovy** [comment]
Hi!

Yes, the units can be quite confusing, but in the case that you are describing, I _think_ the code should give the same outputs whether or not you explicitly set `ro` and `vo` (at least if you set them to defaults: `ro=8.` and `vo=220.`). Could you provide a self-contained example to diagnose the problem?

**Comment by jobovy** [comment]
Thanks for providing the example, I know understand what's going wrong.

The issue is that when you are using non-default values for `ro` and `vo`, you have to specify them for each object that you initialize. So you have to also use them when setting up the `NFWPotential` and the `ChandrasekharDynamicalFrictionForce` (alternatively, you can change the defaults in the [configuration file](https://docs.galpy.org/en/latest/installation.html#configuration-file)). Otherwise, the unit systems of different objects are incompatible. So you can get your `o_2` to agree with `o_1` by re-setting up the potential as
```
from galpy.util.conversion import get_physical
nfw_potential = NFWPotential(conc=10,mvir=1,H=70,Om=0.3089,overdens=200,wrtcrit=True,**get_physical(o_2))
df = ChandrasekharDynamicalFrictionForce(GMs=10**10*u.solMass,dens=nfw_potential,**get_physical(o_2))
```
before integrating `o_2`. The `get_physical` utility function is just so you make sure to use the same `ro` and `vo` as the `o_2` object. 


Now, the code is not supposed to run silently with inconsistent unit systems, but rather throw an error when you try to integrate an orbit with a potential with incompatible units. But this is a case that slipped through the checks, because in the way you are setting up the `NFWPotential`, physical units are not actually turned on (because you don't use Quantities as inputs and you don't set `ro` and `vo`). So if you had done
```
nfw_potential = NFWPotential(conc=10,mvir=1,H=70,Om=0.3089,overdens=200,wrtcrit=True,ro=8.,vo=220.)
```
then the `o_2` orbit integration would have thrown an error. Unfortunately, currently there is no way to set up an `NFWPotential` using `conc` and `mvir` that also automatically turns on units.

Please leave this issue open, because I think I will want to push some changes to avoid this kind of confusion in the future...

**Comment by kassidy-kollmann** [comment]
Thank you, the two orbits do match now! I wanted to clarify what you meant about physical units not actually being turned on with the way I am defining the NFWPotential? In the current version of my code (before doing any of this testing with/without ro and vo), I am doing the orbit integration in the form of the o_1 orbit I defined above. So I am not specifying ro or vo anywhere, and I am using astropy units for all of the initial positions and velocities in the Orbit function, but astropy units do not appear anywhere in the NFWPotential.

`nfw_potential = NFWPotential(conc=10,mvir=1,H=70,Om=0.3089,overdens=200,wrtcrit=True)`
`df = ChandrasekharDynamicalFrictionForce(GMs=10**10*u.solMass,dens=nfw_potential)`

`o = Orbit([R_sat,vR_sat,vphi_sat,z_sat,vZ_sat,phi_sat])`
`ts = np.linspace(1,10,10000)*u.Gyr`
`o.integrate(ts,nfw_potential+df,method='odeint')`

Is the way I defined the potential here incompatible with the way I am evolving the orbit? (I do have astropy-units set to True in the configuration file).

**Comment by jobovy** [comment]
Yes, you are initializing the `NFWPotential` the way you are supposed to, but I agree that it's a bug. `galpy` should turn on physical outputs when you use `mvir` and `conc`, because `mvir` is given in physical units (1e12 Msun). The reason it doesn't turn on units is because the inputs aren't `astropy` Quantities, but the potential is still used wrong if you then use another set of unit conversion parameters. If `galpy` did turn on units, your original issue wouldn't have occurred, because you would have gotten an incompatible-units error. I'll fix this bug, but for now the best thing to do is to explicitly set `ro` and `vo` when initializing the `NFWPotential`. 

This `NFWPotential` initialization is a special case and I think this is the only instance in the code where physical inputs are allowed that aren't `astropy` Quantities.

**Comment by kassidy-kollmann** [comment]
Okay, thank you so much for your help, and for your quick responses! I really appreciate it.
