### ISSUE TITLE
Installing the TorusMapper on macOS

### ISSUE THREAD

**Issue by smeingast** [jobovy/galpy#474]
Dear dev team! I have a working installation of galpy + torusmapper on Ubuntu 20.04.4, however, I am running into issues installing the torus mapper code on macOS 12. The code compiles without any errors or warnings and the C extension module of galpy itself works as intended. Even the library file (libgalpy_actionAngleTorus.so) is generated, yet it seems that the linking process did not work at some point. Specifically, when I try to load the library with 

`import ctypes`
`ctypes.CDLL("/path/to/libgalpy_actionAngleTorus.so")`

I get the error `symbol not found in flat namespace '__ZNSi10_M_extractIdEERSiRT_'` which appears to be responsible for not loading the library correctly (doing the same with libgalpy.so works). My knowledge does not run deep enough to determine whether the issue is on my side, so any help would be appreciated! Thanks!

**Comment by jobovy** [comment]
Hi Stefan,

Glad to hear that you are trying to use `galpy` for this. I'm not sure what's going on and I should say that `galpy` only provides an interface to the [torus](https://github.com/PaulMcMillan-Astro/Torus) code and it could be that your problem is really with that code rather than code directly in `galpy`.

I just compiled the torus extension on my Mac OS 12.3, ARM64 mac and it works for me. Are you using an Intel-based or an M1-based Mac?

It seems like the issue is a missing symbol in the shared library. I don't have this symbol in my shared library (nothing with 'extract' in it, note that the name is mangled by the C++ compiler), so I'm not sure what it is. Looking at the original Torus code, there seems to be an 'extract' function in their main driver, but this isn't used in the `galpy` wrapper and not included in the version of the code that `galpy` installs. Is it possible that you somehow have the original Torus code interfering?

To get some info on what's going on, you can run
```
nm /path/to/libgalpy_actionAngleTorus.so
```
which should show all symbols, including the undefined one. But you can check whether other symbols are defined. All of the `galpy` potentials should be defined (e.g., `_LogarithmicHaloPotentialEval`, C names are not mangled). If much more is undefined, there's probably a bigger problem with the linker. Note that it's normal that there is a bunch of stuff that's undefined, but things like the potential functions shouldn't be undefined.

You can also do
```
otool -L /path/to/libgalpy_actionAngleTorus.so
```
which should show all of the libraries that are needed by the shared library (like the GSL, openBLAS, etc.). Maybe something will look weird there.

If this all looks okay, then I'm not sure what the best next step could be, but perhaps trying to install everything in as clean of an environment as you can get might be useful. You never know whether something has happened to your environment that messes things up. You can also try just installing the Torus code itself and seeing whether you can run that. If not, then the problem probably lies with the Torus code itself, if that does work, perhaps something needs to be updated in the wrapper or the version that `galpy` installed (which is a bit behind the Torus dev version).

**Comment by smeingast** [comment]
Dear Jo! Many thanks for your very detailed reply and your suggestions. My installations are also on macOS 12.3.1 and I tested the installation on both ARM and Intel x86 architecture. 

I did now indeed dig a bit deeper and found that the above-mentioned symbol was indeed undefined (but all the potentials were defined) for some reason. Your hint that the current version does work on your end, led me to try to compile both gsl and subsequently galpy with the Xcode compilers. That indeed did result in a working installation and the missing symbol is not referenced anywhere anymore. However, I am not certain why the macports gcc and gsl distributions would end up with such an error... in any case, the issue is clearly on my end and thanks to your quick reply I got everything up and running!

**Comment by jobovy** [comment]
Glad it got resolved! I'm not sure why the macports compilers wouldn't work here, but I think people don't use macports much these days, and have mostly moved onto homebrew. I find that the Mac package managers typically cause a lot of issues, so with my new Mac, I've been trying to get by without any of them and so far (few months in) everything's been fine (mostly I miss `wget`, but `curl -O` is a pretty good stand-in...). Xcode compilers work well and for Python, the `mini-forge` ARM64 conda distribution has everything I've needed so far (`galpy` is also available there, but without the torus part of course).
