### ISSUE TITLE
Positive potential value for MWPotential2014 (related to the potential zero definition for PowerSphericalPotentialwCutoff)

### ISSUE THREAD

**Issue by lwang-astro** [jobovy/galpy#486]
Today one student has tried to evolve a group of orbits using the MWPotential2014 and found that some bound orbits have positive energy obtained from `.E()` function, which looks incosistent. We have investigated the potential calculation of MWPotential2014 and found that the potential zero for `PowerSphericalPotentialwCutoff` is chosen at (`R=0, z=0`) while the potential zero for other two components (halo, disk) are chosen at inifite distance. Thus, some far-away bound stars have positive potentials, and thus, the total energies are also positive. 

An easy modification to avoid positive potential is to remove the positive constant (first term with gamma function) in the potential evalulation function of `PowerSphericalPotentialwCutoff`. For the case of c interface (file `potential/potential_c_ext/PowerSphericalPotentialwCutoff.c`) :

Change 
```
    return amp * 2. * M_PI * pow(rc,3.-alpha) / r * ( r / rc * ( gsl_sf_gamma ( 1. - 0.5 * alpha ) - gsl_sf_gamma_inc ( 1. - 0.5 * alpha , r2 / rc / rc ) ) - ( gsl_sf_gamma ( 1.5 - 0.5 * alpha )   - gsl_sf_gamma_inc ( 1.5 - 0.5 * alpha , r2 / rc / rc) ) );
```
in function `PowerSphericalPotentialwCutoffEval` to 
```
    return amp * 2. * M_PI * pow(rc,3.-alpha) / r * ( r / rc * ( - gsl_sf_gamma_inc ( 1. - 0.5 * alpha , r2 / rc / rc ) ) - ( gsl_sf_gamma ( 1.5 - 0.5 * alpha ) - gsl_sf_gamma_inc ( 1.5 - 0.5 * alp\
  ha , r2 / rc / rc) ) );
 ``` 
 
Then, the potential is always negative at any position. We are not sure whether the current version is designed for some purposes. But it looks not self-consistent for MWPotential2014 (three components have different defintion of potential zero point) and may mislead users who assume a positive energy represents an unbound orbit.

**Comment by jobovy** [comment]
Thanks for raising this and for providing the code to change this! This has come up before (e.g., #206) and my stance so far has been is that it's a bad assumption to assume that potentials approach zero at infinity, because
* Additive constants don't change any physics, so they are arbitrary and when you use the code, you should use it in a way that doesn't make unwarranted assumptions. So you should only ever consider potential differences and energy differences
* Not all potentials can be normalized to go to zero at infinity (e.g., the `LogarithmicHaloPotential`), so it's not possible to have a fully consistent approach throughout `galpy`.
The documentation also does warn about this (e.g., see the warning near the top of the page at https://docs.galpy.org/en/latest/potential.html). As the documentation states, if you don't want to work with energy differences, one option is to define a `NullPotential` that has as its value minus the potential of `MWPotential2014` at infinity and then use `MWPotential+this NullPotential`, which then does go to zero at infinity. 

The main blocker for making the change you suggest is that the `galpy` paper lists an explicit value for the potential of `MWPotential2014`, so that value would then be wrong. I'm reluctant to make the code examples in the `galpy` paper fail.

However, I do see that this is a relatively easy change to make (at least for `PowerSphericalPotentialwCutoff`), so I'll leave this open and think about it a bit more. Ideally, we would change _all_ potentials that can be normalized at infinity to go to zero there, which is more work then I have time for right now. A PR would be welcome. There's already a test that checks that potentials can be evaluated at infinity:

https://github.com/jobovy/galpy/blob/9e219369162484cd058b98d4ad2ece9939dadf88/tests/test_potential.py#L1411-L1420

and it would thus be straightforward to add a similar test that potentials go to zero at infinity. That could be the starting point to figuring out which potentials would need to be changed.
