### ISSUE TITLE
Physical outputs with interpolatedSphericalPotential

### ISSUE THREAD

**Issue by taliaoshea** [jobovy/galpy#502]
Hi!

We are working on implementing our own potential in galpy using the interpSphericalPotential (based on a galaxy cluster mass profile), but it seems that when we initialize the potential, the density that galpy returns is different from the density we would expect from the enclosed masses we used to create the potential, as shown in the plot below. The difference between the density curves isn't a constant factor, but they do have similar shapes. We aren't sure where the issue is, and would really appreciate any insights you might have about how galpy is using the input force function. I am not sure if it might be related to the choice of scale factor, since right now we have a pretty unphysical set of `ro` and `vo` values? Alternatively maybe we are not converting out of internal units correctly (though I believe I followed your previous advice on converting)? I have attached the code that we used. Thank you so much!!

![output](https://user-images.githubusercontent.com/87497123/187491016-6a44aa54-e2f7-472e-b90c-e615bd855c9f.png)

The code is linked here: https://gist.github.com/taliaoshea/ffddb91d02c3905c94a990354f2441bc

**Comment by jobovy** [comment]
Hi!

Yes, I think the issue here is that the force that you give to `interpSphericalPotential` is in internal units (and has to be evaluated using r in internal units). Changing the relevant code to this seems to work:
```
from galpy.util import conversion
mass_conversion= conversion.mass_in_msol(voVal.to_value(u.km/u.s),roVal.to_value(u.kpc))
def forceFcn(r):
    force = (-1) * enclosedMassInterp(r*roVal.to_value(u.kpc))/mass_conversion / (r**2)
    return force
haloPotential = interpSphericalPotential(
    rforce=forceFcn,
    rgrid=np.geomspace(0.01, 100000, num=200),
    ro=roVal,
    vo=voVal,
)
```
With this I get
<img width="581" alt="Screen Shot 2022-08-30 at 2 48 02 PM" src="https://user-images.githubusercontent.com/1044876/187518423-98b4bade-264d-436a-a42a-7b42399e413a.png">

The `mass_conversion` function gives the relevant factor to go from internal units to Msun, so dividing by it does Msun --> internal. I then also evaluate the enclosed mass at `r*roVal.to_value(u.kpc)` so `r` is in internal units.

I guess the documentation of `interpSphericalPotential` doesn't make it clear that the force needs to be in internal units, so I'll keep this open until I fix that.

**Comment by jobovy** [comment]
I've updated the documentation, so if the issue is resolved, please close.

**Comment by taliaoshea** [comment]
Thank you so much for the help and the documentation update, I'll close the issue now!
