### ISSUE TITLE
Use System's PaulMcMillan-Astro/Torus where it's posible

### ISSUE THREAD

**Issue by Hellseher** [jobovy/galpy#561]
### Description
During preparing the project for Guix I've faced with the issue where
`PaulMcMillan-Astro/Torus` may be provided on system level quite easily but the
build process of galpy is over complicates the build process and there is no way  to use system wide
librariy of Torus.

### Additional context
It would be good benefit for downstream package maintainer to have an option to
use available system packages with less efforts. Good practice is use global
envar like it's achieved in Astropy.

https://github.com/astropy/astropy/blob/ce126277f42396e55b27653d4de88af8c6324d5e/docs/install.rst#external-c-libraries

**Comment by jobovy** [comment]
Yes, we use a customized version of the torus code, with edits made such that the code can be easily linked to from within ``galpy``. I think it probably would be possible to just compile against a system version, but I haven't tested this and definitely not with the latest versions. I don't have any bandwidth to deal with this and don't think I will for a long time. I don't think it actually creates any conflict though to use this customized version, because it is only used within ``galpy``.
