### ISSUE TITLE
`sigmalos` errors with potential as argument

### ISSUE THREAD

**Issue by cgarling** [jobovy/galpy#682]
## 🐛 Bug

`galpy.df.jeans.sigmalos` errors when provided with a potential from `galpy.potential` while `galpy.df.jeans.sigmar` does not.

### Reproducible example

```
import astropy.units as u
from galpy.potential import PlummerPotential
from galpy.df.jeans import sigmar, sigmalos
prof = PlummerPotential(1693*u.solMass, b=100*u.pc)
print(sigmar(prof, 1.0*u.pc, beta=0.0)) # 0.1030855301393923 km/s
print(sigmalos(prof, 1.0*u.pc, beta=0.0)) # errors
print(sigmalos(prof, 1.0, beta=0.0)) # also errors without unit
```

### Expected behavior

Docstrings indicate that `galpy.df.jeans.sigmalos` should be able to take the same arguments as `sigmar` but it errors instead.

### System Details

Ran on the galpy REPL at https://www.galpy.org/repl
Version info is

Emscripten-3.1.14-wasm32-32bit
Python 3.10.2 (main, Aug 29 2022, 18:09:32) [Clang 15.0.0 (https://github.com/llvm/llvm-project 7effcbda49ba32991b8955821b8f
numpy 1.22.4
scipy 1.8.1
matplotlib 3.5.2
galpy 1.10.1.dev0
astropy 5.1

### Additional context

Stacktrace seems to point to some unit-related code but `sigmalos` also errors when `R` is a plain number.

**Comment by jobovy** [comment]
Thanks for reporting this! Yes, there's a minor bug in the `jeans.sigmalos` code where it isn't consistently using internal units. For now, you can do
```python
prof.turn_physical_off()
print(sigmalos(prof, 1.0*u.pc, beta=0.0,use_physical=True,ro=8.,vo=220.))
```
and you'll get output in km/s as you would if the code worked properly. For some reason this doesn't seem to work on the REPL, but I think it should work when you run the code locally. I think this doesn't work in the REPL because of an issue with the ``scipy`` version that is used in the browser (which has known issues with numerical integrals that are irrelevant to the regular Python version of ``scipy``).
